# Generated by Django 5.0.8 on 2024-09-03 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
